<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

### Exercise 1 (Total Recall) 

|**Term**|**Brief Description**|
|:-------|:--------------------|
|Subsetting|Selecting values from the stored data|
|Indexing|Selecting a single value from the stored data|
|Slicing|Selecting a range of values from the stored data|
|Masking|Using True/False to select values from stored data|


### Exercise 2 (Show me the 'odd' letters)

In [2]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [5]:
arr_int = np_array_2d[:, 0].astype(int)

In [1]:
odd_mask = arr_int % 2 == 1
print(odd_mask)
np_array_letters = np_array_2d[odd_mask,1]
print(np_array_letters)


NameError: name 'arr_int' is not defined

### Exercise 3 

In [18]:
array = np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])

In [20]:
result = np.empty_like(array)
result[array <50] = -1
result[array >50] = 1
result[array==50] = 0
print(result)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
