<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

### Exercise 1 (Total Recall) 

|**Term**|**Brief Description**|
|:-------|:--------------------|
|Subsetting|Selecting values from the stored data|
|Indexing|Selecting a single value from the stored data|
|Slicing|Selecting a range of values from the stored data|
|Masking|Using True/False to select values from stored data|


### Exercise 2 (Show me the 'odd' letters)

In [2]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [5]:
arr_int = np_array_2d[:, 0].astype(int)

In [7]:
arr_int % 2 == 0 

array([False, False,  True,  True, False, False,  True,  True,  True,
       False])

In [10]:
print(np_array_2d[0][1], np_array_2d[1][1], np_array_2d[4][1], np_array_2d[5][1], np_array_2d[9][1])

A C E G I


### Exercise 3 

In [18]:
array = np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])

In [20]:
result = np.empty_like(array)
result[array <50] = -1
result[array >50] = 1
result[array==50] = 0
print(result)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
